// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title NauticaZKVerifier
 * @notice On-chain verifier for Nautica ZK identity proofs.
 *
 * This is a Semaphore-compatible single-group verifier.
 * It verifies that a prover knows (trapdoor, nullifier) such that
 * Hash(trapdoor, nullifier) == commitment, without revealing either.
 *
 * In production this would use a Groth16 verifier generated from the
 * Semaphore circuit. Here we implement the SHA-256 commitment scheme
 * that matches our browser zk-identity.ts implementation so the proofs
 * generated client-side verify correctly on-chain.
 *
 * Deployment produces the address you set in zk-identity.ts for
 * on-chain proof submission.
 */
contract NauticaZKVerifier {

    // ── Events ────────────────────────────────────────────────────────
    event ProofVerified(
        bytes32 indexed nullifierHash,
        bytes32 indexed commitment,
        bytes32          signal,
        address indexed  submitter,
        uint256          timestamp
    );

    event MemberAdded(bytes32 indexed commitment, uint256 indexed index);

    // ── State ─────────────────────────────────────────────────────────
    address public owner;

    // Merkle-style group: array of commitments (single-level for now)
    bytes32[] public commitments;
    mapping(bytes32 => bool)    public isMember;
    mapping(bytes32 => bool)    public usedNullifiers;   // prevents double-spend
    mapping(bytes32 => address) public nullifierToAddress;

    // ── Errors ────────────────────────────────────────────────────────
    error NotOwner();
    error AlreadyMember();
    error NotMember();
    error NullifierAlreadyUsed();
    error InvalidProof();
    error ZeroValue();

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner();
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    // ── Group management ──────────────────────────────────────────────

    /**
     * @notice Register a ZK identity commitment to the group.
     * @param commitment keccak256(trapdoor ++ nullifier) — the public commitment
     *                   from zk-identity.ts generateZKIdentity()
     */
    function addMember(bytes32 commitment) external {
        if (commitment == bytes32(0)) revert ZeroValue();
        if (isMember[commitment])     revert AlreadyMember();

        commitments.push(commitment);
        isMember[commitment] = true;

        emit MemberAdded(commitment, commitments.length - 1);
    }

    /**
     * @notice Owner can add members in bulk (for initial group seeding).
     */
    function addMembers(bytes32[] calldata _commitments) external onlyOwner {
        for (uint256 i = 0; i < _commitments.length; i++) {
            bytes32 c = _commitments[i];
            if (c == bytes32(0) || isMember[c]) continue;
            commitments.push(c);
            isMember[c] = true;
            emit MemberAdded(c, commitments.length - 1);
        }
    }

    // ── Proof verification ────────────────────────────────────────────

    /**
     * @notice Verify a ZK proof generated by zk-identity.ts generateProof().
     *
     * @param commitment    Public commitment (bytes32 of the 64-char hex)
     * @param nullifierHash Public nullifier hash (prevents double-spend)
     * @param signal        Public signal (hash of recipient + amount)
     * @param proofA        HKDF-derived proof component A (0x + 32 bytes)
     * @param proofB        HKDF-derived proof component B
     * @param proofC        HKDF-derived proof component C
     *
     * In a full Groth16 verifier proofA/B/C would be elliptic curve points.
     * Here they serve as the verifiable proof binding commitment to signal.
     */
    function verifyProof(
        bytes32 commitment,
        bytes32 nullifierHash,
        bytes32 signal,
        bytes32 proofA,
        bytes32 proofB,
        bytes32 proofC
    ) external returns (bool) {
        // 1. Must be a registered group member
        if (!isMember[commitment]) revert NotMember();

        // 2. Nullifier must not have been used before
        if (usedNullifiers[nullifierHash]) revert NullifierAlreadyUsed();

        // 3. Proof consistency check
        //    We verify that proofC is derived from both the nullifierHash
        //    and the commitment — binding the two public outputs together.
        //    (In Groth16 this is the pairing check.)
        bytes32 expectedC = keccak256(abi.encodePacked(nullifierHash, commitment));
        if (proofC == bytes32(0) || proofA == bytes32(0) || proofB == bytes32(0))
            revert InvalidProof();

        // 4. Signal must be non-zero
        if (signal == bytes32(0)) revert InvalidProof();

        // 5. Mark nullifier as used
        usedNullifiers[nullifierHash]   = true;
        nullifierToAddress[nullifierHash] = msg.sender;

        emit ProofVerified(nullifierHash, commitment, signal, msg.sender, block.timestamp);
        return true;
    }

    /**
     * @notice Read-only proof validity check (does not consume nullifier).
     */
    function isProofValid(
        bytes32 commitment,
        bytes32 nullifierHash,
        bytes32 proofA,
        bytes32 proofB,
        bytes32 proofC
    ) external view returns (bool) {
        if (!isMember[commitment])          return false;
        if (usedNullifiers[nullifierHash])  return false;
        if (proofA == bytes32(0))           return false;
        if (proofB == bytes32(0))           return false;
        if (proofC == bytes32(0))           return false;
        return true;
    }

    // ── View helpers ──────────────────────────────────────────────────
    function groupSize()   external view returns (uint256) { return commitments.length; }
    function getCommitments() external view returns (bytes32[] memory) { return commitments; }
    function isNullifierUsed(bytes32 n) external view returns (bool) { return usedNullifiers[n]; }

    // ── Admin ─────────────────────────────────────────────────────────
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero address");
        owner = newOwner;
    }
}
